const { colors } = require("./modules/colors");

const legends = {
  covidQ1: [
    {
      name: "Increased a lot",
      color: colors.good,
      symbol: "rect",
      units: "percent",
      column: 3,
    },
    {
      name: "Increased somewhat",
      color: colors.ok,
      symbol: "rect",
      units: "percent",
      column: 4,
    },
    {
      name: "Stayed the same",
      color: colors.neutral,
      symbol: "rect",
      units: "percent",
      column: 5,
    },
    {
      name: "Decreased somewhat",
      color: colors.warn,
      symbol: "rect",
      units: "percent",
      column: 6,
    },
    {
      name: "Decreased a lot",
      color: colors.bad,
      symbol: "rect",
      units: "percent",
      column: 7,
    },
  ],
  covidQ3: [
    {
      name: "Approve",
      color: colors.good,
      symbol: "rect",
      units: "percent",
      column: 16,
    },
    {
      name: "Disapprove",
      color: colors.bad,
      symbol: "rect",
      units: "percent",
      column: 17,
    },
    {
      name: "No opinion",
      color: colors.warn,
      symbol: "rect",
      units: "percent",
      column: 18,
    },
  ],
};

const groups = {
  covidQ1: [
    [
      "Increased a lot",
      "Increased somewhat",
      "Stayed the same",
      "Decreased somewhat",
      "Decreased a lot",
    ],
  ],
};

const chartConfig = {
  "q1-gender": {
    chartId: "q1-gender",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 1,
    lastDataColumn: 3,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-age": {
    chartId: "q1-age",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 3,
    lastDataColumn: 6,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-region": {
    chartId: "q1-region",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 6,
    lastDataColumn: 10,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-race": {
    chartId: "q1-race",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 10,
    lastDataColumn: 14,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-education": {
    chartId: "q1-education",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 14,
    lastDataColumn: 18,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-marital-status": {
    chartId: "q1-marital-status",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 18,
    lastDataColumn: 29,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-parent": {
    chartId: "q1-parent",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 29,
    lastDataColumn: 34,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-income": {
    chartId: "q1-income",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 34,
    lastDataColumn: 38,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  "q1-social-networks": {
    chartId: "q1-social-networks",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 38,
    lastDataColumn: 55,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ1,
    groups: groups.covidQ1,
  },
  // Q2
  "q2-social-networks": {
    chartId: "q2-social-networks",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 25,
    firstDataColumn: 38,
    lastDataColumn: 55,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "Yes, I have",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 12,
      },
      {
        name: "No, I haven't",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 13,
      },
    ],
    groups: [["Yes, I have", "No, I haven't"]],
  },
  "q2-gender": {
    chartId: "q2-gender",
    firstDataRow: 19,
    lastDataRow: 20,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "Male",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 2,
      },
      {
        name: "Female",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 3,
      },
    ],
  },
  "q2-age": {
    chartId: "q2-age",
    firstDataRow: 19,
    lastDataRow: 20,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "18-34",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 4,
      },
      {
        name: "35-54",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 5,
      },
      {
        name: "55+",
        color: colors.categoryColors[2],
        symbol: "rect",
        units: "percent",
        column: 6,
      },
    ],
  },
  "q2-region": {
    chartId: "q2-region",
    firstDataRow: 19,
    lastDataRow: 20,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "Northeast",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 7,
      },
      {
        name: "Midwest",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 8,
      },
      {
        name: "South",
        color: colors.categoryColors[2],
        symbol: "rect",
        units: "percent",
        column: 9,
      },
      {
        name: "West",
        color: colors.categoryColors[3],
        symbol: "rect",
        units: "percent",
        column: 10,
      },
    ],
  },
  "q2-race": {
    chartId: "q2-race",
    firstDataRow: 19,
    lastDataRow: 20,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "White",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 11,
      },
      {
        name: "Black",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 12,
      },
      {
        name: "Hispanic",
        color: colors.categoryColors[2],
        symbol: "rect",
        units: "percent",
        column: 13,
      },
      {
        name: "Other (NET)",
        color: colors.categoryColors[3],
        symbol: "rect",
        units: "percent",
        column: 14,
      },
    ],
  },
  "q2-education": {
    chartId: "q2-education",
    firstDataRow: 19,
    lastDataRow: 20,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "No HS, High school graduate",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 15,
      },
      {
        name: "Some college, 2-year",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 16,
      },
      {
        name: "4-year",
        color: colors.categoryColors[2],
        symbol: "rect",
        units: "percent",
        column: 17,
      },
      {
        name: "Post Grad",
        color: colors.categoryColors[3],
        symbol: "rect",
        units: "percent",
        column: 18,
      },
    ],
  },
  "q2-income": {
    chartId: "q2-income",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 25,
    firstDataColumn: 34,
    lastDataColumn: 37,
    maxValue: 99,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "Yes, I have",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 12,
      },
      {
        name: "No, I haven't",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 13,
      },
    ],
    groups: [["Yes, I have", "No, I haven't"]],
  },
  "q2-parent": {
    chartId: "q2-parent",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 25,
    firstDataColumn: 29,
    lastDataColumn: 33,
    maxValue: 99,
    sheet: 2,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "Yes, I have",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 12,
      },
      {
        name: "No, I haven't",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 13,
      },
    ],
    groups: [["Yes, I have", "No, I haven't"]],
  },
  "q2-marital-status": {
    chartId: "q2-parent",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 25,
    firstDataColumn: 18,
    lastDataColumn: 28,
    sheet: 2,
    maxValue: 99,
    // minValue: 0,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: [
      {
        name: "Yes, I have",
        color: colors.categoryColors[0],
        symbol: "rect",
        units: "percent",
        column: 12,
      },
      {
        name: "No, I haven't",
        color: colors.categoryColors[1],
        symbol: "rect",
        units: "percent",
        column: 13,
      },
    ],
    groups: [["Yes, I have", "No, I haven't"]],
  },
  // Q3
  "q3-gender": {
    chartId: "q3-gender",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 1,
    lastDataColumn: 3,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-age": {
    chartId: "q3-age",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 3,
    lastDataColumn: 6,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-region": {
    chartId: "q3-region",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 6,
    lastDataColumn: 10,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-race": {
    chartId: "q3-race",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 10,
    lastDataColumn: 14,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-education": {
    chartId: "q3-education",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 14,
    lastDataColumn: 18,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-marital-status": {
    chartId: "q3-marital-status",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 18,
    lastDataColumn: 29,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-parent": {
    chartId: "q3-parent",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 29,
    lastDataColumn: 34,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-income": {
    chartId: "q3-income",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 34,
    lastDataColumn: 38,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
  "q3-social-networks": {
    chartId: "q3-social-networks",
    transpose: true,
    firstDataRow: 5,
    lastDataRow: 30,
    firstDataColumn: 38,
    lastDataColumn: 55,
    sheet: 2,
    maxValue: 99,
    rotateAxis: true,
    unitSuffix: "%",
    chartColors: {
      axisLabel: colors.main,
    },
    legends: legends.covidQ3,
    groups: [["Approve", "Disapprove", "No opinion"]],
  },
};

module.exports = { chartConfig };
